{{- range .Values.images -}}
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: "{{ .name }}"
spec:
  cloudCredentialsRef:
    cloudName: "{{ .Values.identityRef.cloudName }}"
    secretName: "{{ .Values.identityRef.name }}"
  managementPolicy: managed
  resource:
    properties:
      hardware:
        diskBus: scsi
        scsiModel: virtio-scsi
        vifModel: virtio
        qemuGuestAgent: true
        rngModel: virtio
      architecture: x86_64
      minDiskGB: 20
      minMemoryMB: 2048
      operatingSystem:
        distro: ubuntu
        version: "{{ .ubuntuVersion }}"
    # hypervisorType: kvm # kvm not officially supported, could use qemu
    content:
      diskFormat: qcow2
      download:
        url: {{ .url }}
        hash:
          algorithm: {{ .hash.algorithm }}
          value: {{ .hash.value }}
{{- end -}}